### ISSUE TITLE
Authentication in config file is useless

### ISSUE THREAD

**Issue by dynamiccarrots** [ckfinder/ckfinder-laravel-package#11]
I have CKFinder up and running in my project perfectly, but the issue arose when I came to secure it. 

The Authentication part is inside the config file, I can not access the session in this file and I can not check for my admin flag in the user's table here. 

How do I overcome this?

**Comment by zaak** [comment]
This issue has been fixed in the latest version. Authentication uses now a middleware: https://github.com/ckfinder/ckfinder-laravel-package#configuring-authentication.

**Comment by aaadkins** [comment]
Even with the new middleware I still cannot access the session and auth::user() returns null.  Is there something else I need to do?  So currently I cannot secure it or setup private folders.
